---
- name: Install Neovim
  become: yes
  package:
    name: neovim
    state: present

- name: create config dir
  file:
    path: ~/.config/nvim
    state: directory

- name: create local dir
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Install plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Configure neovim
  template:
    src: dot.vimrc.j2
    dest: ~/.config/nvim/init.vim
