---
- name: Check for rust
  stat:
    path: ~/.cargo/env
  register: rust

- name: download rustup script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755
  when: rust.stat.exists == False

- name: execute rustup script
  shell: /tmp/rustup.sh -y
  args:
    creates: ~/.cargo/env
  when: rust.stat.exists == False
